/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/items': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Test Front */
		get: operations['test_front_items_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Read Root
		 * @description A simple root endpoint to confirm the server is reachable.
		 */
		get: operations['read_root__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Api Status
		 * @description Endpoint to check the general status of the API.
		 */
		get: operations['api_status_api_status_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/protected': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Protected Route */
		get: operations['protected_route_api_auth_protected_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/refresh': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Refresh Access Token
		 * @description Refreshes the Access Token using a valid Refresh Token.
		 */
		post: operations['refresh_access_token_api_auth_refresh_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/connect/google': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Connect Google */
		get: operations['connect_google_api_auth_connect_google_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/callback/google': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Callback Google */
		get: operations['callback_google_api_auth_callback_google_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/ai/interpret': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Interpret Command
		 * @description Main endpoint. Receives user's text, sends it to the AI,
		 *     and returns a structured workflow definition or an error.
		 */
		post: operations['interpret_command_api_ai_interpret_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/ai/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health
		 * @description Health check endpoint to verify Azure connection
		 */
		get: operations['health_api_ai_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/webhooks/listen-to-gmail': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Listen Gmail
		 * @description Initiate the webhook to get gmail push notifications
		 */
		get: operations['listen_gmail_api_webhooks_listen_to_gmail_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/webhooks/gmail': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Gmail Webhook
		 * @description Receives push notifications from Google Cloud Pub/Sub.
		 */
		post: operations['gmail_webhook_api_webhooks_gmail_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/get_workflows': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Workflows
		 * @description Get a list of the all the workflows from the current user
		 */
		get: operations['get_workflows_api_workflow_get_workflows_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/run': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Run Workflow */
		post: operations['run_workflow_api_workflow_run_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/toggle': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Toggle Workflow
		 * @description Pause or Resume a Prefect deployment and updates the status of the workflow in the database.
		 */
		patch: operations['toggle_workflow_api_workflow_toggle_patch'];
		trace?: never;
	};
	'/api/workflow/update-config': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Update Workflow Config
		 * @description Update the parameters/config of a specific Prefect deployment and also it's workflow corresponding entity.
		 */
		patch: operations['update_workflow_config_api_workflow_update_config_patch'];
		trace?: never;
	};
	'/api/workflow/delete': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete Workflow
		 * @description Deletes a workflow from the database and deletes it's deployment from Prefect
		 */
		delete: operations['delete_workflow_api_workflow_delete_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** AIResponse */
		AIResponse: {
			/** Success */
			success: boolean;
			data?: components['schemas']['WorkflowDefinition'] | null;
			/** Error */
			error?: string | null;
		};
		/** Action */
		Action: {
			/** @description The type of action to perform */
			type: components['schemas']['ActionType'];
			/**
			 * Config
			 * @description The configuration needed for this action, like channel name, email address, etc.
			 */
			config: {
				[key: string]: unknown;
			};
		};
		/**
		 * ActionType
		 * @enum {string}
		 */
		ActionType:
			| 'send_slack_message'
			| 'send_email'
			| 'reply_email'
			| 'label_email'
			| 'smart_draft'
			| 'create_document';
		/** DeleteWorkflowRequest */
		DeleteWorkflowRequest: {
			/**
			 * Deployment Id
			 * Format: uuid
			 * @description The Prefect Deployment ID
			 */
			deployment_id: string;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/** RefreshTokenRequest */
		RefreshTokenRequest: {
			/** Refresh Token */
			refresh_token: string;
		};
		/** RunWorkflowRequest */
		RunWorkflowRequest: {
			/**
			 * Deployment Id
			 * Format: uuid
			 * @description The Prefect Deployment ID
			 */
			deployment_id: string;
			/**
			 * Config
			 * @description Workflow parameters
			 */
			config: {
				[key: string]: unknown;
			};
		};
		/** ToggleWorkflowRequest */
		ToggleWorkflowRequest: {
			/**
			 * Deployment Id
			 * Format: uuid
			 * @description The Prefect Deployment ID
			 */
			deployment_id: string;
			/**
			 * Status
			 * @description True to Resume (Active), False to Pause
			 */
			status: boolean;
		};
		/** Token */
		Token: {
			/** Access Token */
			access_token: string;
			/** Refresh Token */
			refresh_token: string;
			/** Token Type */
			token_type: string;
		};
		/** Trigger */
		Trigger: {
			/** @description The event that starts the workflow */
			type: components['schemas']['TriggerType'];
			/**
			 * Config
			 * @description The configuration needed for this trigger, like sender's email, sheet ID, etc.
			 */
			config: {
				[key: string]: unknown;
			};
		};
		/**
		 * TriggerType
		 * @enum {string}
		 */
		TriggerType: 'email_received' | 'new_sheet_row' | 'schedule';
		/** UpdateWorkflowRequest */
		UpdateWorkflowRequest: {
			/**
			 * Deployment Id
			 * Format: uuid
			 * @description The Prefect Deployment ID
			 */
			deployment_id: string;
			/**
			 * Config
			 * @description New configuration/parameters to merge
			 */
			config: {
				[key: string]: unknown;
			};
		};
		/** UserRequest */
		UserRequest: {
			/** Text */
			text: string;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
		};
		/** WorkflowDefinition */
		WorkflowDefinition: {
			/**
			 * Name
			 * @description A concise, descriptive name for this workflow
			 */
			name: string;
			/**
			 * Description
			 * @description A one-sentence summary of the workflow's purpose
			 */
			description: string;
			trigger: components['schemas']['Trigger'];
			/** Actions */
			actions: components['schemas']['Action'][];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	test_front_items_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	read_root__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	api_status_api_status_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	protected_route_api_auth_protected_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	refresh_access_token_api_auth_refresh_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RefreshTokenRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Token'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	connect_google_api_auth_connect_google_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	callback_google_api_auth_callback_google_get: {
		parameters: {
			query: {
				code: string;
				state: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	interpret_command_api_ai_interpret_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UserRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AIResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	health_api_ai_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	listen_gmail_api_webhooks_listen_to_gmail_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	gmail_webhook_api_webhooks_gmail_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	get_workflows_api_workflow_get_workflows_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	run_workflow_api_workflow_run_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RunWorkflowRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	toggle_workflow_api_workflow_toggle_patch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ToggleWorkflowRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	update_workflow_config_api_workflow_update_config_patch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateWorkflowRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_workflow_api_workflow_delete_delete: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DeleteWorkflowRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
