/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/auth/protected': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Protected Route */
		get: operations['protected_route_api_auth_protected_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/refresh': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Refresh Access Token
		 * @description Refreshes the Access Token using a valid Refresh Token.
		 */
		post: operations['refresh_access_token_api_auth_refresh_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/connect/google': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Connect Google */
		get: operations['connect_google_api_auth_connect_google_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/callback/google': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Callback Google */
		get: operations['callback_google_api_auth_callback_google_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/connection/status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Connection Status
		 * @description Returns the connectivity status of all supported integrations for the current user.
		 */
		get: operations['get_connection_status_api_connection_status_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/ai/interpret': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Interpret Command
		 * @description Main endpoint. Receives user's text, sends it to the AI,
		 *     and returns a structured workflow definition or an error.
		 */
		post: operations['interpret_command_api_ai_interpret_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/ai/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health
		 * @description Health check endpoint to verify Azure connection
		 */
		get: operations['health_api_ai_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/webhooks/listen-to-gmail': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Listen Gmail
		 * @description Initiate the webhook to get gmail push notifications
		 */
		get: operations['listen_gmail_api_webhooks_listen_to_gmail_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/webhooks/gmail': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Gmail Webhook
		 * @description Receives push notifications from Google Cloud Pub/Sub.
		 */
		post: operations['gmail_webhook_api_webhooks_gmail_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/catalog': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Catalog
		 * @description Returns a structured manifest of all available trigger and action nodes,
		 *     including their field definitions and UI metadata (category, icon).
		 *     Designed for the frontend catalog-driven editor to consume.
		 */
		get: operations['get_catalog_api_workflow_catalog_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/get_workflows': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Workflows
		 * @description Get a list of the all the workflows from the current user
		 */
		get: operations['get_workflows_api_workflow_get_workflows_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/get_workflow/{workflow_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Workflow */
		get: operations['get_workflow_api_workflow_get_workflow__workflow_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/run': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Run Workflow */
		post: operations['run_workflow_api_workflow_run_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/toggle': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Toggle Workflow
		 * @description Pause or Resume a Prefect deployment and updates the status of the workflow in the database.
		 */
		patch: operations['toggle_workflow_api_workflow_toggle_patch'];
		trace?: never;
	};
	'/api/workflow/create': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create Workflow
		 * @description Register a new workflow in Prefect and save it to the local database.
		 */
		post: operations['create_workflow_api_workflow_create_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/update-config': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Update Workflow Config
		 * @description Update the parameters/config of a specific Prefect deployment and also it's workflow corresponding entity.
		 */
		patch: operations['update_workflow_config_api_workflow_update_config_patch'];
		trace?: never;
	};
	'/api/workflow/delete': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete Workflow
		 * @description Deletes a workflow from the database and deletes it's deployment from Prefect
		 */
		delete: operations['delete_workflow_api_workflow_delete_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/histories': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Workflow Histories
		 * @description Fetches the history of all the deployments of the user
		 */
		get: operations['get_workflow_histories_api_workflow_histories_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/{deployement_id}/history': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Workflow History
		 * @description Fetches only the history for a specific deployment
		 */
		get: operations['get_workflow_history_api_workflow__deployement_id__history_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/runs/latest': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Latest Runs
		 * @description Lightweight endpoint for frontend polling.
		 *     Checks the most recent runs to trigger toast notifications.
		 */
		get: operations['get_latest_runs_api_workflow_runs_latest_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/runs/{run_id}/logs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Run Logs
		 * @description Fetches the full terminal logs for a specific execution.
		 *     Used when a user clicks the 'Eye' icon or 'View Logs' button.
		 */
		get: operations['get_run_logs_api_workflow_runs__run_id__logs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/test-notification/{user_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Test Notification
		 * @description Push a test notification to a specific user via WebSocket.
		 */
		post: operations['test_notification_api_workflow_test_notification__user_id__post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** AIResponse */
		AIResponse: {
			/** Success */
			success: boolean;
			data?: components['schemas']['WorkflowSchema-Output'] | null;
			/** Error */
			error?: string | null;
		};
		/**
		 * ConditionOperators
		 * @enum {string}
		 */
		ConditionOperators: 'equals' | 'contains' | 'exists' | 'greater_than' | 'less_than';
		/** ConditionRule */
		ConditionRule: {
			/**
			 * Variable
			 * @description e.g., '{{trigger_1.subject}}'
			 */
			variable: string;
			operator: components['schemas']['ConditionOperators'];
			/** Value */
			value: unknown;
		};
		/** ConnectionStatusResponse */
		ConnectionStatusResponse: {
			/** Integrations */
			integrations: components['schemas']['IntegrationStatus'][];
		};
		/** CreateDocumentAction */
		CreateDocumentAction: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'create_document';
			config: components['schemas']['CreateDocumentConfig'];
		};
		/** CreateDocumentConfig */
		CreateDocumentConfig: {
			/** Title */
			title: string;
			/** Content */
			content: string;
		};
		/** Edge */
		Edge: {
			/** Id */
			id: string;
			/** Source */
			source: string;
			/** Target */
			target: string;
			/**
			 * Sourcehandle
			 * @description Used for Condition Nodes to route logic (e.g., 'true_path', 'false_path')
			 */
			sourceHandle?: string | null;
			/** Targethandle */
			targetHandle?: string | null;
		};
		/** EmailReceivedConfig */
		EmailReceivedConfig: {
			/** From */
			from?: string | null;
			/** Subject Contains */
			subject_contains?: string | null;
		};
		/** EmailReceivedTrigger */
		EmailReceivedTrigger: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'email_received';
			config: components['schemas']['EmailReceivedConfig'];
		};
		/** FieldDefinition */
		FieldDefinition: {
			/** Key */
			key: string;
			/** Label */
			label: string;
			/** Type */
			type: string;
			/** Required */
			required: boolean;
			/** Default */
			default?: unknown;
			/**
			 * Description
			 * @default
			 */
			description: string;
			/** Options */
			options?: string[] | null;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/** IfCondition */
		'IfCondition-Input': {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'if_condition';
			config: components['schemas']['IfConditionConfig-Input'];
		};
		/** IfCondition */
		'IfCondition-Output': {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'if_condition';
			config: components['schemas']['IfConditionConfig-Output'];
		};
		/** IfConditionConfig */
		'IfConditionConfig-Input': {
			/** Rules */
			rules: components['schemas']['ConditionRule'][];
			/**
			 * Match Type
			 * @default ALL
			 * @enum {string}
			 */
			match_type: 'ANY' | 'ALL';
		};
		/** IfConditionConfig */
		'IfConditionConfig-Output': {
			/** Rules */
			rules: components['schemas']['ConditionRule'][];
			/**
			 * Match Type
			 * @default ALL
			 * @enum {string}
			 */
			match_type: 'ANY' | 'ALL';
		};
		/** IntegrationStatus */
		IntegrationStatus: {
			/**
			 * Provider
			 * @description The name of the integration (e.g., 'google', 'discord')
			 */
			provider: string;
			/**
			 * Is Connected
			 * @description True if the user has connected this account
			 */
			is_connected: boolean;
			/**
			 * Email
			 * @description The email associated with the connected account
			 */
			email?: string | null;
			/**
			 * Needs Reconnect
			 * @description True if tokens are invalid and user must log in again
			 */
			needs_reconnect: boolean;
		};
		/** LabelEmailAction */
		LabelEmailAction: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'label_email';
			config: components['schemas']['LabelEmailConfig'];
		};
		/** LabelEmailConfig */
		LabelEmailConfig: {
			/**
			 * Label Name
			 * @description The name of the label (e.g., 'OFFERS')
			 */
			label_name: string;
			/**
			 * Background Color
			 * @default #999999
			 */
			background_color: string;
			/**
			 * Text Color
			 * @default #f3f3f3
			 */
			text_color: string;
		};
		/** ManualConfig */
		ManualConfig: {
			/**
			 * Description
			 * @default Triggered manually via the UI
			 */
			description: string;
		};
		/** ManualTrigger */
		ManualTrigger: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'manual';
			config: components['schemas']['ManualConfig'];
		};
		/** NewSheetRowConfig */
		NewSheetRowConfig: {
			/** Spreadsheet Id */
			spreadsheet_id: string;
		};
		/** NewSheetRowTrigger */
		NewSheetRowTrigger: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'new_sheet_row';
			config: components['schemas']['NewSheetRowConfig'];
		};
		/** NodeDefinition */
		NodeDefinition: {
			/** Type */
			type: string;
			/** Category */
			category: string;
			/** Label */
			label: string;
			/** Icon */
			icon: string;
			/** Description */
			description: string;
			/** Fields */
			fields: components['schemas']['FieldDefinition'][];
			/** Outputs */
			outputs?: string[];
		};
		/** RefreshTokenRequest */
		RefreshTokenRequest: {
			/** Refresh Token */
			refresh_token: string;
		};
		/** ReplyEmailAction */
		ReplyEmailAction: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'reply_email';
			config: components['schemas']['ReplyEmailConfig'];
		};
		/** ReplyEmailConfig */
		ReplyEmailConfig: {
			/** Body */
			body: string;
		};
		/** RunWorkflowRequest */
		RunWorkflowRequest: {
			/**
			 * Deployment Id
			 * Format: uuid
			 * @description The Prefect Deployment ID
			 */
			deployment_id: string;
			/**
			 * Config
			 * @description Workflow parameters
			 */
			config?: {
				[key: string]: unknown;
			};
		};
		/** ScheduleConfig */
		ScheduleConfig: {
			/**
			 * Cron
			 * @example 0 9 * * *
			 */
			cron: string;
			/** Description */
			description: string;
		};
		/** ScheduleTrigger */
		ScheduleTrigger: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'schedule';
			config: components['schemas']['ScheduleConfig'];
		};
		/** SendEmailAction */
		SendEmailAction: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'send_email';
			config: components['schemas']['SendEmailConfig'];
		};
		/** SendEmailConfig */
		SendEmailConfig: {
			/**
			 * To
			 * Format: email
			 */
			to: string;
			/** Subject */
			subject: string;
			/** Body */
			body: string;
		};
		/** SendSlackMessageAction */
		SendSlackMessageAction: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'send_slack_message';
			config: components['schemas']['SendSlackMessageConfig'];
		};
		/** SendSlackMessageConfig */
		SendSlackMessageConfig: {
			/**
			 * Channel
			 * @description Channel name or ID (e.g., #general)
			 */
			channel: string;
			/** Message */
			message: string;
		};
		/** SmartDraftAction */
		SmartDraftAction: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'smart_draft';
			config: components['schemas']['SmartDraftConfig'];
		};
		/** SmartDraftConfig */
		SmartDraftConfig: {
			/** User Prompt */
			user_prompt: string;
		};
		/** ToggleWorkflowRequest */
		ToggleWorkflowRequest: {
			/**
			 * Deployment Id
			 * Format: uuid
			 * @description The Prefect Deployment ID
			 */
			deployment_id: string;
			/**
			 * Status
			 * @description True to Resume (Active), False to Pause
			 */
			status: boolean;
		};
		/** Token */
		Token: {
			/** Access Token */
			access_token: string;
			/** Refresh Token */
			refresh_token: string;
			/** Token Type */
			token_type: string;
		};
		/** UIMetadata */
		UIMetadata: {
			/** Nodes */
			nodes: {
				[key: string]: unknown;
			}[];
			/** Edges */
			edges: {
				[key: string]: unknown;
			}[];
			/** Viewport */
			viewport?: {
				[key: string]: unknown;
			} | null;
		};
		/** UpdateWorkflowRequest */
		UpdateWorkflowRequest: {
			/**
			 * Deployment Id
			 * Format: uuid
			 * @description The Prefect Deployment ID
			 */
			deployment_id: string;
			/** @description New configuration/parameters to merge */
			schema: components['schemas']['WorkflowSchema-Input'];
		};
		/** UserRequest */
		UserRequest: {
			/** Text */
			text: string;
			current_workflow: components['schemas']['WorkflowSchema-Input'] | null;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
		};
		/** WorkflowCatalog */
		WorkflowCatalog: {
			/** Triggers */
			triggers: components['schemas']['NodeDefinition'][];
			/** Actions */
			actions: components['schemas']['NodeDefinition'][];
			/** Conditions */
			conditions: components['schemas']['NodeDefinition'][];
		};
		/** WorkflowExecutionConfig */
		'WorkflowExecutionConfig-Input': {
			/**
			 * Start Node Ids
			 * @description List of Node IDs that represent triggers capable of starting this graph.
			 */
			start_node_ids: string[];
			/**
			 * Nodes
			 * @description A dictionary mapping node_id to the Node object for O(1) lookups.
			 */
			nodes: {
				[key: string]: components['schemas']['WorkflowNode-Input'];
			};
			/**
			 * Edges
			 * @description Flat list of edges connecting the nodes.
			 */
			edges?: components['schemas']['Edge'][];
		};
		/** WorkflowExecutionConfig */
		'WorkflowExecutionConfig-Output': {
			/**
			 * Start Node Ids
			 * @description List of Node IDs that represent triggers capable of starting this graph.
			 */
			start_node_ids: string[];
			/**
			 * Nodes
			 * @description A dictionary mapping node_id to the Node object for O(1) lookups.
			 */
			nodes: {
				[key: string]: components['schemas']['WorkflowNode-Output'];
			};
			/**
			 * Edges
			 * @description Flat list of edges connecting the nodes.
			 */
			edges?: components['schemas']['Edge'][];
		};
		/** WorkflowNode */
		'WorkflowNode-Input': {
			/** Id */
			id: string;
			/** Name */
			name?: string | null;
			/**
			 * Type
			 * @enum {string}
			 */
			type: 'trigger' | 'action' | 'condition';
			/** Config */
			config:
				| components['schemas']['EmailReceivedTrigger']
				| components['schemas']['ManualTrigger']
				| components['schemas']['NewSheetRowTrigger']
				| components['schemas']['ScheduleTrigger']
				| components['schemas']['SendSlackMessageAction']
				| components['schemas']['SendEmailAction']
				| components['schemas']['ReplyEmailAction']
				| components['schemas']['LabelEmailAction']
				| components['schemas']['SmartDraftAction']
				| components['schemas']['CreateDocumentAction']
				| components['schemas']['IfCondition-Input'];
		};
		/** WorkflowNode */
		'WorkflowNode-Output': {
			/** Id */
			id: string;
			/** Name */
			name?: string | null;
			/**
			 * Type
			 * @enum {string}
			 */
			type: 'trigger' | 'action' | 'condition';
			/** Config */
			config:
				| components['schemas']['EmailReceivedTrigger']
				| components['schemas']['ManualTrigger']
				| components['schemas']['NewSheetRowTrigger']
				| components['schemas']['ScheduleTrigger']
				| components['schemas']['SendSlackMessageAction']
				| components['schemas']['SendEmailAction']
				| components['schemas']['ReplyEmailAction']
				| components['schemas']['LabelEmailAction']
				| components['schemas']['SmartDraftAction']
				| components['schemas']['CreateDocumentAction']
				| components['schemas']['IfCondition-Output'];
		};
		/** WorkflowRun */
		WorkflowRun: {
			/**
			 * Id
			 * Format: uuid
			 * @description The Prefect run id.
			 */
			id: string;
			/**
			 * Name
			 * @description The name of the flow run.
			 */
			name: string;
			/**
			 * Deployment Id
			 * @description The ID of the associated deployment.
			 */
			deployment_id?: string | null;
			/**
			 * State Name
			 * @description The name of the current flow run state.
			 */
			state_name?: string | null;
			/**
			 * Start Time
			 * @description The actual start time.
			 */
			start_time?: string | null;
			/**
			 * Total Run Time
			 * @description Total run time in seconds.
			 * @default 0
			 */
			total_run_time: number;
		};
		/**
		 * WorkflowSchema
		 * @description The full representation used by the API and AI Service.
		 */
		'WorkflowSchema-Input': {
			/**
			 * Name
			 * @description A concise, descriptive name for this workflow
			 */
			name: string;
			/**
			 * Description
			 * @description A one-sentence summary of the workflow's purpose
			 */
			description: string;
			/**
			 * Is Active
			 * @default true
			 */
			is_active: boolean;
			execution_config: components['schemas']['WorkflowExecutionConfig-Input'];
			ui_metadata?: components['schemas']['UIMetadata'] | null;
		};
		/**
		 * WorkflowSchema
		 * @description The full representation used by the API and AI Service.
		 */
		'WorkflowSchema-Output': {
			/**
			 * Name
			 * @description A concise, descriptive name for this workflow
			 */
			name: string;
			/**
			 * Description
			 * @description A one-sentence summary of the workflow's purpose
			 */
			description: string;
			/**
			 * Is Active
			 * @default true
			 */
			is_active: boolean;
			execution_config: components['schemas']['WorkflowExecutionConfig-Output'];
			ui_metadata?: components['schemas']['UIMetadata'] | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	protected_route_api_auth_protected_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	refresh_access_token_api_auth_refresh_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RefreshTokenRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Token'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	connect_google_api_auth_connect_google_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	callback_google_api_auth_callback_google_get: {
		parameters: {
			query: {
				code: string;
				state: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_connection_status_api_connection_status_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ConnectionStatusResponse'];
				};
			};
		};
	};
	interpret_command_api_ai_interpret_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UserRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AIResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	health_api_ai_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	listen_gmail_api_webhooks_listen_to_gmail_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	gmail_webhook_api_webhooks_gmail_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	get_catalog_api_workflow_catalog_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkflowCatalog'];
				};
			};
		};
	};
	get_workflows_api_workflow_get_workflows_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	get_workflow_api_workflow_get_workflow__workflow_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				workflow_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	run_workflow_api_workflow_run_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RunWorkflowRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	toggle_workflow_api_workflow_toggle_patch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ToggleWorkflowRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_workflow_api_workflow_create_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkflowSchema-Input'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	update_workflow_config_api_workflow_update_config_patch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateWorkflowRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_workflow_api_workflow_delete_delete: {
		parameters: {
			query: {
				deployment_id: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_workflow_histories_api_workflow_histories_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkflowRun'][];
				};
			};
		};
	};
	get_workflow_history_api_workflow__deployement_id__history_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				deployement_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkflowRun'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_latest_runs_api_workflow_runs_latest_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkflowRun'][];
				};
			};
		};
	};
	get_run_logs_api_workflow_runs__run_id__logs_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	test_notification_api_workflow_test_notification__user_id__post: {
		parameters: {
			query?: {
				message?: string;
			};
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
