/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/auth/protected': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Protected Route */
		get: operations['protected_route_api_auth_protected_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/refresh': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Refresh Access Token
		 * @description Refreshes the Access Token using a valid Refresh Token.
		 */
		post: operations['refresh_access_token_api_auth_refresh_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/connect/google': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Connect Google */
		get: operations['connect_google_api_auth_connect_google_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/callback/google': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Callback Google */
		get: operations['callback_google_api_auth_callback_google_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/ai/interpret': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Interpret Command
		 * @description Main endpoint. Receives user's text, sends it to the AI,
		 *     and returns a structured workflow definition or an error.
		 */
		post: operations['interpret_command_api_ai_interpret_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/ai/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health
		 * @description Health check endpoint to verify Azure connection
		 */
		get: operations['health_api_ai_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/webhooks/listen-to-gmail': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Listen Gmail
		 * @description Initiate the webhook to get gmail push notifications
		 */
		get: operations['listen_gmail_api_webhooks_listen_to_gmail_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/webhooks/gmail': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Gmail Webhook
		 * @description Receives push notifications from Google Cloud Pub/Sub.
		 */
		post: operations['gmail_webhook_api_webhooks_gmail_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/get_workflows': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Workflows
		 * @description Get a list of the all the workflows from the current user
		 */
		get: operations['get_workflows_api_workflow_get_workflows_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/run': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Run Workflow */
		post: operations['run_workflow_api_workflow_run_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workflow/toggle': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Toggle Workflow
		 * @description Pause or Resume a Prefect deployment and updates the status of the workflow in the database.
		 */
		patch: operations['toggle_workflow_api_workflow_toggle_patch'];
		trace?: never;
	};
	'/api/workflow/update-config': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Update Workflow Config
		 * @description Update the parameters/config of a specific Prefect deployment and also it's workflow corresponding entity.
		 */
		patch: operations['update_workflow_config_api_workflow_update_config_patch'];
		trace?: never;
	};
	'/api/workflow/delete': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete Workflow
		 * @description Deletes a workflow from the database and deletes it's deployment from Prefect
		 */
		delete: operations['delete_workflow_api_workflow_delete_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** AIResponse */
		AIResponse: {
			/** Success */
			success: boolean;
			data?: components['schemas']['WorkflowDefinition-Output'] | null;
			/** Error */
			error?: string | null;
		};
		/** CreateDocumentAction */
		CreateDocumentAction: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'create_document';
			config: components['schemas']['CreateDocumentConfig'];
		};
		/** CreateDocumentConfig */
		CreateDocumentConfig: {
			/** Title */
			title: string;
			/** Content */
			content: string;
		};
		/** DeleteWorkflowRequest */
		DeleteWorkflowRequest: {
			/**
			 * Deployment Id
			 * Format: uuid
			 * @description The Prefect Deployment ID
			 */
			deployment_id: string;
		};
		/** EmailReceivedConfig */
		EmailReceivedConfig: {
			/**
			 * From
			 * Format: email
			 */
			from: string;
			/**
			 * Subject Contains
			 * @default
			 */
			subject_contains: string;
		};
		/** EmailReceivedTrigger */
		EmailReceivedTrigger: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'email_received';
			config: components['schemas']['EmailReceivedConfig'];
		};
		/** GmailLabel */
		GmailLabel: {
			/** Name */
			name: string;
			labelListVisibility?: components['schemas']['LabelListVisibility'] | null;
			messageListVisibility?: components['schemas']['MessageListVisibility'] | null;
			type?: components['schemas']['LabelType'] | null;
			color?: components['schemas']['LabelColor'] | null;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/** LabelColor */
		LabelColor: {
			/**
			 * Backgroundcolor
			 * @description The background color hex string (e.g., #000000)
			 */
			backgroundColor: string;
			/**
			 * Textcolor
			 * @description The text color hex string (e.g., #ffffff)
			 */
			textColor: string;
		};
		/** LabelEmailAction */
		'LabelEmailAction-Input': {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'label_email';
			config: components['schemas']['LabelEmailConfig-Input'];
		};
		/** LabelEmailAction */
		'LabelEmailAction-Output': {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'label_email';
			config: components['schemas']['LabelEmailConfig-Output'];
		};
		/** LabelEmailConfig */
		'LabelEmailConfig-Input': {
			label_info: components['schemas']['GmailLabel'];
		};
		/** LabelEmailConfig */
		'LabelEmailConfig-Output': {
			label_info: components['schemas']['GmailLabel'];
		};
		/**
		 * LabelListVisibility
		 * @enum {string}
		 */
		LabelListVisibility: 'labelShow' | 'labelShowIfUnread' | 'labelHide';
		/**
		 * LabelType
		 * @enum {string}
		 */
		LabelType: 'system' | 'user';
		/**
		 * MessageListVisibility
		 * @enum {string}
		 */
		MessageListVisibility: 'show' | 'hide';
		/** NewSheetRowConfig */
		NewSheetRowConfig: {
			/** Spreadsheet Id */
			spreadsheet_id: string;
		};
		/** NewSheetRowTrigger */
		NewSheetRowTrigger: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'new_sheet_row';
			config: components['schemas']['NewSheetRowConfig'];
		};
		/** RefreshTokenRequest */
		RefreshTokenRequest: {
			/** Refresh Token */
			refresh_token: string;
		};
		/** ReplyEmailAction */
		ReplyEmailAction: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'reply_email';
			config: components['schemas']['ReplyEmailConfig'];
		};
		/** ReplyEmailConfig */
		ReplyEmailConfig: {
			/** Body */
			body: string;
		};
		/** RunWorkflowRequest */
		RunWorkflowRequest: {
			/**
			 * Deployment Id
			 * Format: uuid
			 * @description The Prefect Deployment ID
			 */
			deployment_id: string;
			/**
			 * Config
			 * @description Workflow parameters
			 */
			config: {
				[key: string]: unknown;
			};
		};
		/** ScheduleConfig */
		ScheduleConfig: {
			/**
			 * Cron
			 * @example 0 9 * * *
			 */
			cron: string;
			/** Description */
			description: string;
		};
		/** ScheduleTrigger */
		ScheduleTrigger: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'schedule';
			config: components['schemas']['ScheduleConfig'];
		};
		/** SendEmailAction */
		SendEmailAction: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'send_email';
			config: components['schemas']['SendEmailConfig'];
		};
		/** SendEmailConfig */
		SendEmailConfig: {
			/**
			 * To
			 * Format: email
			 */
			to: string;
			/** Subject */
			subject: string;
			/** Body */
			body: string;
		};
		/** SendSlackMessageAction */
		SendSlackMessageAction: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'send_slack_message';
			config: components['schemas']['SendSlackMessageConfig'];
		};
		/** SendSlackMessageConfig */
		SendSlackMessageConfig: {
			/**
			 * Channel
			 * @description Channel name or ID (e.g., #general)
			 */
			channel: string;
			/** Message */
			message: string;
		};
		/** SmartDraftAction */
		SmartDraftAction: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: 'smart_draft';
			config: components['schemas']['SmartDraftConfig'];
		};
		/** SmartDraftConfig */
		SmartDraftConfig: {
			/** User Prompt */
			user_prompt: string;
		};
		/** ToggleWorkflowRequest */
		ToggleWorkflowRequest: {
			/**
			 * Deployment Id
			 * Format: uuid
			 * @description The Prefect Deployment ID
			 */
			deployment_id: string;
			/**
			 * Status
			 * @description True to Resume (Active), False to Pause
			 */
			status: boolean;
		};
		/** Token */
		Token: {
			/** Access Token */
			access_token: string;
			/** Refresh Token */
			refresh_token: string;
			/** Token Type */
			token_type: string;
		};
		/** UIMetadata */
		UIMetadata: {
			/** Nodes */
			nodes: {
				[key: string]: unknown;
			}[];
			/** Edges */
			edges: {
				[key: string]: unknown;
			}[];
			/** Viewport */
			viewport?: {
				[key: string]: unknown;
			} | null;
		};
		/** UpdateWorkflowRequest */
		UpdateWorkflowRequest: {
			/**
			 * Deployment Id
			 * Format: uuid
			 * @description The Prefect Deployment ID
			 */
			deployment_id: string;
			/** @description New configuration/parameters to merge */
			config: components['schemas']['WorkflowDefinition-Input'];
		};
		/** UserRequest */
		UserRequest: {
			/** Text */
			text: string;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
		};
		/** WorkflowDefinition */
		'WorkflowDefinition-Input': {
			/**
			 * Name
			 * @description A concise, descriptive name for this workflow
			 */
			name: string;
			/**
			 * Description
			 * @description A one-sentence summary of the workflow's purpose
			 */
			description: string;
			/** Trigger */
			trigger:
				| components['schemas']['EmailReceivedTrigger']
				| components['schemas']['NewSheetRowTrigger']
				| components['schemas']['ScheduleTrigger'];
			/** Actions */
			actions: (
				| components['schemas']['SendSlackMessageAction']
				| components['schemas']['SendEmailAction']
				| components['schemas']['ReplyEmailAction']
				| components['schemas']['LabelEmailAction-Input']
				| components['schemas']['SmartDraftAction']
				| components['schemas']['CreateDocumentAction']
			)[];
			ui_metadata?: components['schemas']['UIMetadata'] | null;
		};
		/** WorkflowDefinition */
		'WorkflowDefinition-Output': {
			/**
			 * Name
			 * @description A concise, descriptive name for this workflow
			 */
			name: string;
			/**
			 * Description
			 * @description A one-sentence summary of the workflow's purpose
			 */
			description: string;
			/** Trigger */
			trigger:
				| components['schemas']['EmailReceivedTrigger']
				| components['schemas']['NewSheetRowTrigger']
				| components['schemas']['ScheduleTrigger'];
			/** Actions */
			actions: (
				| components['schemas']['SendSlackMessageAction']
				| components['schemas']['SendEmailAction']
				| components['schemas']['ReplyEmailAction']
				| components['schemas']['LabelEmailAction-Output']
				| components['schemas']['SmartDraftAction']
				| components['schemas']['CreateDocumentAction']
			)[];
			ui_metadata?: components['schemas']['UIMetadata'] | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	protected_route_api_auth_protected_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	refresh_access_token_api_auth_refresh_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RefreshTokenRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Token'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	connect_google_api_auth_connect_google_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	callback_google_api_auth_callback_google_get: {
		parameters: {
			query: {
				code: string;
				state: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	interpret_command_api_ai_interpret_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UserRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AIResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	health_api_ai_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	listen_gmail_api_webhooks_listen_to_gmail_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	gmail_webhook_api_webhooks_gmail_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	get_workflows_api_workflow_get_workflows_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	run_workflow_api_workflow_run_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RunWorkflowRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	toggle_workflow_api_workflow_toggle_patch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ToggleWorkflowRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	update_workflow_config_api_workflow_update_config_patch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateWorkflowRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_workflow_api_workflow_delete_delete: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DeleteWorkflowRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
