"""add auth_codes table

Revision ID: 433ce5d966d4
Revises: a1b2c3d4e5f6
Create Date: 2026-06-16 18:50:19.406651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433ce5d966d4'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_codes_code'), 'auth_codes', ['code'], unique=True)
    op.drop_constraint(op.f('oauth_states_state_key'), 'oauth_states', type_='unique')
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=False)
    op.create_unique_constraint(op.f('oauth_states_state_key'), 'oauth_states', ['state'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_auth_codes_code'), table_name='auth_codes')
    op.drop_table('auth_codes')
    # ### end Alembic commands ###
