"""set nullable to true for access token

Revision ID: 45c50d63932a
Revises: cba185ee478d
Create Date: 2026-01-06 12:54:42.049212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c50d63932a'
down_revision: Union[str, Sequence[str], None] = 'cba185ee478d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connected_accounts', 'access_token',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connected_accounts', 'access_token',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
