"""add last_synced_started_at column to connected accounts

Revision ID: a7d9c8b49d32
Revises: f9c7e4416427
Create Date: 2026-01-13 10:23:24.434125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d9c8b49d32'
down_revision: Union[str, Sequence[str], None] = 'f9c7e4416427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_accounts', sa.Column('last_synced_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connected_accounts', 'last_synced_started_at')
    # ### end Alembic commands ###
