"""Add is_connected column

Revision ID: c7182be5a11f
Revises: 3a0100fb10ef
Create Date: 2026-01-06 10:35:07.228941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7182be5a11f'
down_revision: Union[str, Sequence[str], None] = '3a0100fb10ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('connected_accounts', sa.Column('is_connected', sa.Boolean(), nullable=True))
    op.execute("UPDATE connected_accounts SET is_connected = FALSE")
    op.alter_column('connected_accounts', 'is_connected', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connected_accounts', 'is_connected')
    # ### end Alembic commands ###
