"""add code_verifier to oauth_states

Revision ID: d2efb512a727
Revises: f4a5b6c7d8e9
Create Date: 2026-08-01 11:01:12.463754

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2efb512a727"
down_revision: Union[str, Sequence[str], None] = "f4a5b6c7d8e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth_states", sa.Column("code_verifier", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth_states", "code_verifier")
    # ### end Alembic commands ###
