"""rename ai_generated_defenition to config

Revision ID: efcfbfffdb2c
Revises: 4aecc30d62be
Create Date: 2025-12-23 14:22:30.434115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efcfbfffdb2c'
down_revision: Union[str, Sequence[str], None] = '4aecc30d62be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('workflows', 'ai_generated_definition')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('ai_generated_definition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('workflows', 'config')
    # ### end Alembic commands ###
