"""remove column constraint and add composite unique constraint

Revision ID: f1acf193f5d6
Revises: a7d9c8b49d32
Create Date: 2026-01-13 14:26:58.580046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1acf193f5d6'
down_revision: Union[str, Sequence[str], None] = 'a7d9c8b49d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('processed_messages_message_id_key'), 'processed_messages', type_='unique')
    op.drop_constraint(op.f('processed_messages_workflow_id_key'), 'processed_messages', type_='unique')
    op.create_unique_constraint('uq_message_workflow_pair', 'processed_messages', ['message_id', 'workflow_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_message_workflow_pair', 'processed_messages', type_='unique')
    op.create_unique_constraint(op.f('processed_messages_workflow_id_key'), 'processed_messages', ['workflow_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('processed_messages_message_id_key'), 'processed_messages', ['message_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
