"""rename status column into is_active

Revision ID: f9c7e4416427
Revises: 45c50d63932a
Create Date: 2026-01-07 17:16:04.328633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c7e4416427'
down_revision: Union[str, Sequence[str], None] = '45c50d63932a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workflows", "status", new_column_name="is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workflows", "is_active", new_column_name="status")
    # ### end Alembic commands ###
